version: '2.0'
services:
  mongodb:
    image: mongo:3.2.17
    command: mongod --port 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
      - ./data/sqlite:/data/sqlite
    ports:
      - 27017:27017
  chromedriver:
    image: robcherry/docker-chromedriver:latest
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=""
    ports:
      - 4444:4444
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=umdio
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  umdio:
    build: .
    depends_on:
      - mongodb
      - postgres
    links:
      - mongodb
      - postgres
    environment:
      - MONGO_RUBY_DRIVER_HOST=mongodb
      - MONGO_RUBY_DRIVER_PORT=27017
    volumes:
      - ./:/umdio
    ports:
      - 3000:3000
    command: bundle exec rake up